# codavox validation lab.
#
# Follows the OpenVox getting-started workflow
# (https://docs.openvoxproject.org/openvox/latest/getting_started.html) and slots
# codavox into the gap it exists for: getting resolved code onto compilers.
#
#   install OpenVox Server -> enrol agents -> control repo -> r10k -> deploy
#
# The one deviation is the r10k remote: a file:// URL against this repo's own .git,
# synced read-only into the primary, so iterating is "commit, then deploy" rather
# than "push, then deploy". Module fetches still reach the network. Everything
# downstream is unaffected, because r10k still produces a real resolved tree.
#
#   Topology                          serves                 gets code from
#   ------------------------------------------------------------------------
#   puppet       192.168.57.10        no agents              r10k (file:// .git)
#   compiler01   192.168.57.11        agent01                codavox agent
#   compiler02   192.168.57.12        nothing yet            codavox agent
#   agent01      192.168.57.13        -                      compiler01
#
# The primary deliberately serves no agents. That is how a real multi-compiler
# estate is laid out, and it keeps static catalogs purely a codavox property —
# there is no node here that could produce a code_id by any other means.
#
# Two compilers, because one can only ever demonstrate convergence. Two can
# demonstrate divergence: stop compiler02's agent, deploy, and `codavox compilers`
# on the primary reports them at different code_ids until it catches up.
#
# 192.168.57.x on purpose: the dev control-repo uses 192.168.56.x, so both labs can
# be up at once without colliding.

Vagrant.configure("2") do |config|
  # Sequential bring-up. The compilers enrol against the primary's CA and poll its
  # publisher, so the primary has to be finished before they start.
  ENV['VAGRANT_NO_PARALLEL'] ||= '1'

  # Set OPENVOX_TEST_REPO=1 to install from the pre-release testing repository.
  openvox_test_repo = ENV['OPENVOX_TEST_REPO'] == '1'
  yum_release_base = openvox_test_repo \
    ? 'https://s3.osuosl.org/openvox-artifacts/repo_test/yum' \
    : 'https://yum.voxpupuli.org'

  config.vm.box = "bento/centos-stream-10"

  # Written into /etc/hosts on every node. The lab has no DNS, and codavox verifies
  # the publisher's certificate against its certname, so forward resolution has to
  # work for `https://puppet.example.com:8150` to be reachable at all.
  hosts = <<-HOSTS
    192.168.57.10 puppet.example.com puppet
    192.168.57.11 compiler01.example.com compiler01
    192.168.57.12 compiler02.example.com compiler02
    192.168.57.13 agent01.example.com agent01
  HOSTS

  # Common to every node: hosts file, OpenVox repo, clock.
  common = <<-SHELL
    set -euo pipefail

    grep -q compiler01.example.com /etc/hosts || cat >> /etc/hosts <<'EOF'
#{hosts}
EOF

    # Parallels VMs can boot with real clock skew. If the clock is wrong when
    # puppetserver first starts it bakes a bad timestamp into the CRL, which then
    # fails validation as "CRL not yet valid" until it is regenerated by hand —
    # and codavox reads that same CRL on every request, so it would refuse every
    # compiler for reasons that look nothing like a clock problem.
    systemctl stop chronyd 2>/dev/null || true
    chronyd -q 'pool pool.ntp.org iburst' || true
    systemctl start chronyd

    dnf install -y -q curl
    rpm -q openvox8-release >/dev/null 2>&1 || \
      rpm -Uvh #{yum_release_base}/openvox8-release-el-10.noarch.rpm
  SHELL

  # csr_attributes.yaml has to exist before the node's first check-in. pp_role is an
  # X.509 extension, so it is fixed when the certificate is issued and cannot be
  # added afterwards without revoking and re-enrolling. codavox's publisher
  # authorizes on exactly this: a certificate signed by the CA only proves the peer
  # is *some* enrolled node, and every agent in the estate clears that bar.
  csr_attributes = lambda do |role|
    <<-SHELL
      install -d -m 0755 /etc/puppetlabs/puppet
      cat > /etc/puppetlabs/puppet/csr_attributes.yaml <<'EOF'
---
extension_requests:
  pp_role: #{role}
EOF
    SHELL
  end

  # ---------------------------------------------------------------- primary ----
  config.vm.define "puppet" do |node|
    node.vm.hostname = "puppet.example.com"
    node.vm.network "private_network", ip: "192.168.57.10"

    node.vm.provider "parallels" do |prl|
      prl.memory = 3072
      prl.cpus = 2
    end

    # Read-only, and NOT an environment directory. r10k clones from the .git inside
    # it; the working tree is never served. That is the whole difference from the
    # dev control repo, where the working tree *was* the production environment and
    # codavox therefore had a tree full of build artifacts to seal.
    node.vm.synced_folder ".", "/vagrant-src", mount_options: ["ro"]

    node.vm.provision "shell", inline: common
    node.vm.provision "shell", inline: csr_attributes.call("openvox_server")
    node.vm.provision "shell", inline: <<-SHELL
      set -euo pipefail

      dnf install -y -q openvox-server git

      /opt/puppetlabs/bin/puppet config set --section main certname puppet.example.com
      /opt/puppetlabs/bin/puppet config set --section main server puppet.example.com
      /opt/puppetlabs/bin/puppet config set --section server dns_alt_names puppet,puppet.example.com

      # Only these three certnames are autosigned. The guide has you run
      # `puppetserver ca list` and `ca sign --certname` by hand, which is right for
      # a real estate; naming the nodes rather than using `*` keeps the lab
      # non-interactive without accepting anything that asks.
      cat > /etc/puppetlabs/puppet/autosign.conf <<'EOF'
compiler01.example.com
compiler02.example.com
agent01.example.com
EOF

      firewall-cmd --add-port=8140/tcp --permanent >/dev/null
      firewall-cmd --add-port=8150/tcp --permanent >/dev/null
      firewall-cmd --reload >/dev/null

      systemctl enable --now puppetserver

      # r10k, per the guide.
      /opt/puppetlabs/puppet/bin/gem list -i r10k >/dev/null 2>&1 || \
        /opt/puppetlabs/puppet/bin/gem install r10k --no-document

      install -d -m 0755 /etc/puppetlabs/r10k
      cat > /etc/puppetlabs/r10k/r10k.yaml <<'EOF'
---
cachedir: '/var/cache/r10k'

sources:
  control:
    # A file:// remote against the synced checkout's .git. r10k deploys committed
    # branches, so an uncommitted edit is invisible here — which is the point:
    # codavox distributes what was committed, not whatever the host happens to
    # have saved.
    remote: 'file:///vagrant-src/.git'
    basedir: '/etc/puppetlabs/code/environments'
EOF

      # git refuses file:// clones of a repo owned by another uid unless told the
      # path is trusted. The synced mount is owned by the host user.
      git config --global --add safe.directory /vagrant-src
      git config --global --add safe.directory /vagrant-src/.git

      echo "[primary] deploying environments with r10k"
      /opt/puppetlabs/puppet/bin/r10k deploy environment -v -p

      # Converge the primary itself: this installs codavox and starts the
      # publisher, which seals what r10k just deployed.
      /opt/puppetlabs/bin/puppet agent -t --waitforlock 60 || true

      # The agent is left off on every node. This is a lab for watching specific
      # things happen, and a background agent run in the middle of an observation
      # is noise.
      systemctl disable --now puppet 2>/dev/null || true

      echo "[primary] serving:"
      /opt/puppetlabs/bin/codavox compilers 2>/dev/null || true
      journalctl -u codavox-publish --no-pager -n 3 || true
    SHELL
  end

  # -------------------------------------------------------------- compilers ----
  ["compiler01", "compiler02"].each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.hostname = "#{name}.example.com"
      node.vm.network "private_network", ip: "192.168.57.#{11 + i}"

      node.vm.provider "parallels" do |prl|
        prl.memory = 2560
        prl.cpus = 2
      end

      node.vm.provision "shell", inline: common
      node.vm.provision "shell", inline: csr_attributes.call("openvox_compiler")
      node.vm.provision "shell", inline: <<-SHELL
        set -euo pipefail

        dnf install -y -q openvox-server

        /opt/puppetlabs/bin/puppet config set --section main certname #{name}.example.com
        /opt/puppetlabs/bin/puppet config set --section main server puppet.example.com
        /opt/puppetlabs/bin/puppet config set --section main ca_server puppet.example.com

        # A compiler compiles catalogs and serves file content; it does not issue
        # certificates. Removing the CA from the service list is what makes the
        # estate have exactly one authority, and it has to happen before this node
        # holds a certificate.
        BOOTSTRAP=/etc/puppetlabs/puppetserver/services.d/ca.cfg
        install -d -m 0755 /etc/puppetlabs/puppetserver/services.d
        cat > "$BOOTSTRAP" <<'EOF'
# This node defers certificate signing to the primary.
puppetlabs.services.ca.certificate-authority-disabled-service/certificate-authority-disabled-service
EOF

        # Enrol and converge. This installs the codavox agent and, because
        # profile::codavox::compiler wires the server by default, repoints
        # environmentpath at codavox's directory.
        /opt/puppetlabs/bin/puppet agent -t --waitforlock 60 || true

        # Wait for the agent to actually converge before trusting puppetserver.
        # The catalog wires environmentpath in the same run that starts the agent,
        # so the restart it triggers can land before any code has been unpacked —
        # and codavox has no fallback, so compiles would fail until the next poll.
        # Restarting after code-id answers closes that window deterministically
        # rather than relying on timing.
        echo "[#{name}] waiting for codavox to converge"
        for i in $(seq 1 30); do
          if /opt/puppetlabs/bin/codavox code-id production >/dev/null 2>&1; then
            echo "[#{name}] serving $(/opt/puppetlabs/bin/codavox code-id production)"
            break
          fi
          sleep 4
        done
        /opt/puppetlabs/bin/codavox code-id production >/dev/null 2>&1 \
          || { echo "[#{name}] codavox never converged"; journalctl -u codavox-agent --no-pager -n 20; exit 1; }

        systemctl restart puppetserver
        systemctl disable --now puppet 2>/dev/null || true

        # Do not return until puppetserver answers, or agent01's first run races a
        # still-starting JVM and fails for a reason that has nothing to do with it.
        for i in $(seq 1 60); do
          curl -ks https://localhost:8140/status/v1/simple >/dev/null 2>&1 && break
          sleep 5
        done
      SHELL
    end
  end

  # ------------------------------------------------------------------ agent ----
  config.vm.define "agent01" do |node|
    node.vm.hostname = "agent01.example.com"
    node.vm.network "private_network", ip: "192.168.57.13"

    node.vm.provider "parallels" do |prl|
      prl.memory = 1024
      prl.cpus = 1
    end

    node.vm.provision "shell", inline: common
    node.vm.provision "shell", inline: csr_attributes.call("openvox_agent")
    node.vm.provision "shell", inline: <<-SHELL
      set -euo pipefail

      dnf install -y -q openvox-agent

      /opt/puppetlabs/bin/puppet config set --section main certname agent01.example.com
      # Catalogs from a compiler, certificates from the primary. This split is the
      # thing the lab exists to exercise: the compiler can only answer because
      # codavox put code on it.
      /opt/puppetlabs/bin/puppet config set --section main server compiler01.example.com
      /opt/puppetlabs/bin/puppet config set --section main ca_server puppet.example.com

      /opt/puppetlabs/bin/puppet agent -t --waitforlock 60 || true
      systemctl disable --now puppet 2>/dev/null || true

      echo "[agent01] marker:"
      cat /etc/codavox-lab-marker 2>/dev/null || echo "  (not applied)"
      echo "[agent01] catalog code_id:"
      grep -o '"code_id":"[^"]*"' \
        /opt/puppetlabs/puppet/cache/client_data/catalog/agent01.example.com.json \
        2>/dev/null || echo "  (none — not a static catalog)"
    SHELL
  end
end
